'use client';
import { Tournament } from "./page";

export const tournaments: Tournament[] = [
  {
    "id": 1,
    "name": "Desafío Aralar Erronka",
    "results": [
      { category: "MPO", club: "Lekumberri", player: "Rafael Sarriegui Hidalgo", position: 1 },
      { category: "MPO", club: "Lekumberri", player: "Kristopher Vanbogelen", position: 2 },
      { category: "FPO", club: "Lekumberri", player: "Lorea Zulet Ruiz", position: 1 },
      { category: "MP50", club: "Bilbao", player: "David Angulo", position: 1 },
      { category: "MP50", club: "Baxi", player: "Mikel Ibarrola Manterola", position: 2 },
      { category: "MP50", club: "Bilbao", player: "Jose Sampedro Santin", position: 3 },
      { category: "MA3", club: "International", player: "Hugo Rodriguez Fernandez", position: 1 },
      { category: "MA3", club: "Compostela", player: "Pedro Gonzalez Bascoy", position: 2 },
      { category: "MA3", club: "Oviedo", player: "Daniel Díaz Castro", position: 3 },
      { category: "MA3", club: "International", player: "Fraser Ambrose", position: 4 },
      { category: "MA3", club: "International", player: "Armando Del Olmo", position: 5 },
      { category: "MA4", club: "Bilbao", player: "Asier Merino Lekue", position: 1 },
      { category: "MJ18", club: "Bilbao", player: "Beñat Lopez Arribas", position: 1 },
    ]
  },
  {
    "id": 2,
    "name": "Intermad",
    "results": [
      { category: "MPO", club: "Lekumberri", player: "Rafael Sarriegui Hidalgo", position: 4 },
      { category: "MPO", club: "Toros Mijas", player: "Markus Pohjolainen", position: 1 },
      { category: "MPO", club: "Esperit", player: "Marc Lopez Lopez", position: 2 },
      { category: "MPO", club: "Oviedo", player: "Gorka Beltran de Heredia Alvarez", position: 2 },
      { category: "MPO", club: "International", player: "Martin Murray", position: 5 },
      { category: "MPO", club: "Flying", player: "Merlin Sales-Tomas Sales", position: 6 },
      { category: "MPO", club: "International", player: "Jorge BerÁstegui-Sampedro", position: 7 },
      { category: "FPO", club: "Asturias", player: "Ana María Álvarez Menendez", position: 1 },
      { category: "FPO", club: "Osona", player: "Queralt Pinyol", position: 2 },
      { category: "FPO", club: "International", player: "Vanessa Fernandez Fernandez", position: 3 },
      { category: "MP40", club: "International", player: "Robert Abel", position: 1 },
      { category: "MP40", club: "Compostela", player: "Iván Gutiérrez De Terán", position: 2 },
      { category: "MP40", club: "Compostela", player: "Manuel Angel Almeida Posada", position: 2 },
      { category: "MP40", club: "Esperit", player: "David Wilde", position: 4 },
      { category: "MP40", club: "Osona", player: "Marc Font Font", position: 5 },
      { category: "MP40", club: "Compostela", player: "Alejandro Liz Graña", position: 6 },
      { category: "MP50", club: "Bilbao", player: "David Angulo", position: 2 },
      { category: "MP50", club: "Baxi", player: "Iñaki González Olaizola", position: 1 },
      { category: "MP50", club: "Oviedo", player: "Javier Del Riego", position: 3 },
      { category: "MP50", club: "International", player: "Toni Barrientos", position: 4 },
      { category: "MP50", club: "Baxi", player: "Antonio Negrete Gutiérrez", position: 5 },
      { category: "MP50", club: "Esperit", player: "Eloy Gomez Ingelmo", position: 6 },
      { category: "MP50", club: "International", player: "Ismael Rodriguez", position: 7 },
      { category: "MA3", club: "International", player: "Hugo Rodriguez Fernandez", position: 2 },
      { category: "MA3", club: "Oviedo", player: "Daniel Díaz Castro", position: 1 },
      { category: "MA3", club: "International", player: "Fraser Ambrose", position: 7 },
      { category: "MA3", club: "International", player: "Armando Del Olmo", position: 6 },
      { category: "MA3", club: "International", player: "Juan Aramburu", position: 3 },
      { category: "MA3", club: "International", player: "Nelson Zurdo", position: 4 },
      { category: "MA3", club: "International", player: "Stefan Nestelberger", position: 5 },
      { category: "MA3", club: "International", player: "Pepe García", position: 8 },
      { category: "MA3", club: "International", player: "Lucas Rey Braga", position: 9 },
      { category: "MA3", club: "International", player: "Héctor Triano Alcántara", position: 10 },
      { category: "MA3", club: "International", player: "Nacho Ocho", position: 11 },
      { category: "MA3", club: "Asturias", player: "Jorge Almeida", position: 11 },
      { category: "MA4", club: "International", player: "Arturo García Rodrigo", position: 1 },
      { category: "MA4", club: "International", player: "Rubén Hoya", position: 2 },
      { category: "MA4", club: "Oviedo", player: "José Francisco Hernández López", position: 3 },
      { category: "MA4", club: "Osona", player: "Ferran Boix Piella", position: 4 },
      { category: "MA4", club: "Oviedo", player: "Javier Lorences Fernandez", position: 5 },
      { category: "MA4", club: "Oviedo", player: "Hernán Fernández Joglar", position: 6 },
      { category: "MA4", club: "Oviedo", player: "Marcos Garcia Almeida", position: 7 },
      { category: "MA4", club: "International", player: "Dennis Neiman", position: 8 },
      { category: "MA4", club: "International", player: "John Turcany", position: 9 },
      { category: "MA4", club: "International", player: "Francisco Panero", position: 10 },
      { category: "MA4", club: "International", player: "Miguel Angel Moral", position: 10 },
      { category: "MA4", club: "International", player: "Eduardo Martín Manzanera", position: 12 },
      { category: "MJ18", club: "Esperit", player: "Lucas Gómez Feijoo", position: 1 }
    ]
  }
];

/* TEMPLATE
[
  {
    "id": 1,
    "name": "Tournament 1",
    "results": [
      { category: "MPO", club: "Lekumberri", player: "Rafael Sarriegui Hidalgo", position: null },
      { category: "MPO", club: "Lekumberri", player: "Kristopher Vanbogelen", position: null },
      { category: "MPO", club: "Toros Mijas", player: "Markus Pohjolainen", position: null },
      { category: "MPO", club: "Esperit", player: "Marc Lopez Lopez", position: null },
      { category: "MPO", club: "Oviedo", player: "Gorka Beltran de Heredia Alvarez", position: null },
      { category: "MPO", club: "International", player: "Martin Murray", position: null },
      { category: "MPO", club: "Flying", player: "Merlin Sales-Tomas Sales", position: null },
      { category: "MPO", club: "International", player: "Jorge BerÁstegui-Sampedro", position: null },
      { category: "FPO", club: "Lekumberri", player: "Lorea Zulet Ruiz", position: null },
      { category: "FPO", club: "Asturias", player: "Ana María Álvarez Menendez", position: null },
      { category: "FPO", club: "Osona", player: "Queralt Pinyol", position: null },
      { category: "FPO", club: "International", player: "Vanessa Fernandez Fernandez", position: null },
      { category: "MP40", club: "International", player: "Robert Abel", position: null },
      { category: "MP40", club: "Compostela", player: "Iván Gutiérrez De Terán", position: null },
      { category: "MP40", club: "Compostela", player: "Manuel Angel Almeida Posada", position: null },
      { category: "MP40", club: "Esperit", player: "David Wilde", position: null },
      { category: "MP40", club: "Osona", player: "Marc Font Font", position: null },
      { category: "MP40", club: "Compostela", player: "Alejandro Liz Graña", position: null },
      { category: "MP50", club: "Bilbao", player: "David Angulo", position: null },
      { category: "MP50", club: "Baxi", player: "Mikel Ibarrola Manterola", position: null },
      { category: "MP50", club: "Bilbao", player: "Jose Sampedro Santin", position: null },
      { category: "MP50", club: "Baxi", player: "Iñaki González Olaizola", position: null },
      { category: "MP50", club: "Oviedo", player: "Javier Del Riego", position: null },
      { category: "MP50", club: "International", player: "Toni Barrientos", position: null },
      { category: "MP50", club: "Baxi", player: "Antonio Negrete Gutiérrez", position: null },
      { category: "MP50", club: "Esperit", player: "Eloy Gomez Ingelmo", position: null },
      { category: "MP50", club: "International", player: "Ismael Rodriguez", position: null },
      { category: "MA3", club: "International", player: "Hugo Rodriguez Fernandez", position: null },
      { category: "MA3", club: "Compostela", player: "Pedro Gonzalez Bascoy", position: null },
      { category: "MA3", club: "Oviedo", player: "Daniel Díaz Castro", position: null },
      { category: "MA3", club: "International", player: "Fraser Ambrose", position: null },
      { category: "MA3", club: "International", player: "Armando Del Olmo", position: null },
      { category: "MA3", club: "International", player: "Juan Aramburu", position: null },
      { category: "MA3", club: "International", player: "Nelson Zurdo", position: null },
      { category: "MA3", club: "International", player: "Stefan Nestelberger", position: null },
      { category: "MA3", club: "International", player: "Pepe García", position: null },
      { category: "MA3", club: "International", player: "Lucas Rey Braga", position: null },
      { category: "MA3", club: "International", player: "Héctor Triano Alcántara", position: null },
      { category: "MA3", club: "International", player: "Nacho Ocho", position: null },
      { category: "MA3", club: "Asturias", player: "Jorge Almeida", position: null },
      { category: "MA4", club: "Bilbao", player: "Asier Merino Lekue", position: null },
      { category: "MA4", club: "International", player: "Arturo García Rodrigo", position: null },
      { category: "MA4", club: "International", player: "Rubén Hoya", position: null },
      { category: "MA4", club: "Oviedo", player: "José Francisco Hernández López", position: null },
      { category: "MA4", club: "Osona", player: "Ferran Boix Piella", position: null },
      { category: "MA4", club: "Oviedo", player: "Javier Lorences Fernandez", position: null },
      { category: "MA4", club: "Oviedo", player: "Hernán Fernández Joglar", position: null },
      { category: "MA4", club: "Oviedo", player: "Marcos Garcia Almeida", position: null },
      { category: "MA4", club: "International", player: "Dennis Neiman", position: null },
      { category: "MA4", club: "International", player: "John Turcany", position: null },
      { category: "MA4", club: "International", player: "Francisco Panero", position: null },
      { category: "MA4", club: "International", player: "Miguel Angel Moral", position: null },
      { category: "MA4", club: "International", player: "Eduardo Martín Manzanera", position: null },
      { category: "MJ18", club: "Bilbao", player: "Beñat Lopez Arribas", position: null },
      { category: "MJ18", club: "Esperit", player: "Lucas Gómez Feijoo", position: null }
    ]
  },
]

 
 */