'use client';
import { Tournament } from "./page";

export const tournaments: Tournament[] = [
  {
    "id": 1,
    "name": "Desafío Aralar Erronka",
    "results": [
      { category: "MPO", club: "Lekunberri Kirol Elkartea", player: "Rafael Sarriegui Hidalgo", position: 1 },
      { category: "MPO", club: "Lekunberri Kirol Elkartea", player: "Kristopher Vanbogelen", position: 2 },
      { category: "FPO", club: "Lekunberri Kirol Elkartea", player: "Lorea Zulet Ruiz", position: 1 },
      { category: "MP40", club: "Madrid international disc golf", player: "Robert Abel", position: 1 },
      { category: "MP50", club: "Bilbao disc golf club", player: "David Angulo", position: 1 },
      { category: "MP50", club: "Baxi Basajauna disc golf Elkartea", player: "Mikel Ibarrola Manterola", position: 2 },
      { category: "MP50", club: "Bilbao disc golf club", player: "Jose Sampedro Santin", position: 3 },
      { category: "MA3", club: "Madrid international disc golf", player: "Hugo Rodriguez Fernandez", position: 1 },
      { category: "MA3", club: "Compostela disc golf club", player: "Pedro Gonzalez Bascoy", position: 2 },
      { category: "MA3", club: "Disc golf club Oviedo", player: "Daniel Díaz Castro", position: 3 },
      { category: "MA3", club: "Madrid international disc golf", player: "Fraser Ambrose", position: 4 },
      { category: "MA3", club: "Madrid international disc golf", player: "Armando Del Olmo", position: 5 },
      { category: "MA4", club: "Bilbao disc golf club", player: "Asier Merino Lekue", position: 1 },
      { category: "MJ18", club: "Bilbao disc golf club", player: "Beñat Lopez Arribas", position: 1 },
    ]
  },
  {
    "id": 2,
    "name": "Intermad",
    "results": [
      { category: "MPO", club: "Lekunberri Kirol Elkartea", player: "Rafael Sarriegui Hidalgo", position: 4 },
      { category: "MPO", club: "Toros Mijas", player: "Markus Pohjolainen", position: 1 },
      { category: "MPO", club: "Esperit disc golf club", player: "Marc Lopez Lopez", position: 2 },
      { category: "MPO", club: "Disc golf club Oviedo", player: "Gorka Beltran de Heredia Alvarez", position: 2 },
      { category: "MPO", club: "Madrid international disc golf", player: "Martin Murray", position: 5 },
      { category: "MPO", club: "Flying squirrels", player: "Merlin Sales-Tomas Sales", position: 6 },
      { category: "MPO", club: "Madrid international disc golf", player: "Jorge BerÁstegui-Sampedro", position: 7 },
      { category: "FPO", club: "Asturias disc golf club", player: "Ana María Álvarez Menendez", position: 1 },
      { category: "FPO", club: "Osona discgolf", player: "Queralt Pinyol", position: 2 },
      { category: "FPO", club: "Madrid international disc golf", player: "Vanessa Fernandez Fernandez", position: 3 },
      { category: "MP40", club: "Madrid international disc golf", player: "Robert Abel", position: 1 },
      { category: "MP40", club: "Compostela disc golf club", player: "Iván Gutiérrez De Terán", position: 2 },
      { category: "MP40", club: "Compostela disc golf club", player: "Manuel Angel Almeida Posada", position: 2 },
      { category: "MP40", club: "Esperit disc golf club", player: "David Wilde", position: 4 },
      { category: "MP40", club: "Osona discgolf", player: "Marc Font Font", position: 5 },
      { category: "MP40", club: "Compostela disc golf club", player: "Alejandro Liz Graña", position: 6 },
      { category: "MP50", club: "Bilbao disc golf club", player: "David Angulo", position: 2 },
      { category: "MP50", club: "Baxi Basajauna disc golf Elkartea", player: "Iñaki González Olaizola", position: 1 },
      { category: "MP50", club: "Disc golf club Oviedo", player: "Javier Del Riego", position: 3 },
      { category: "MP50", club: "Madrid international disc golf", player: "Toni Barrientos", position: 4 },
      { category: "MP50", club: "Baxi Basajauna disc golf Elkartea", player: "Antonio Negrete Gutiérrez", position: 5 },
      { category: "MP50", club: "Esperit disc golf club", player: "Eloy Gomez Ingelmo", position: 6 },
      { category: "MP50", club: "Madrid international disc golf", player: "Ismael Rodriguez", position: 7 },
      { category: "MA3", club: "Madrid international disc golf", player: "Hugo Rodriguez Fernandez", position: 2 },
      { category: "MA3", club: "Disc golf club Oviedo", player: "Daniel Díaz Castro", position: 1 },
      { category: "MA3", club: "Madrid international disc golf", player: "Fraser Ambrose", position: 7 },
      { category: "MA3", club: "Madrid international disc golf", player: "Armando Del Olmo", position: 6 },
      { category: "MA3", club: "Madrid international disc golf", player: "Juan Aramburu", position: 3 },
      { category: "MA3", club: "Madrid international disc golf", player: "Nelson Zurdo", position: 4 },
      { category: "MA3", club: "Madrid international disc golf", player: "Stefan Nestelberger", position: 5 },
      { category: "MA3", club: "Madrid international disc golf", player: "Pepe García", position: 8 },
      { category: "MA3", club: "Madrid international disc golf", player: "Lucas Rey Braga", position: 9 },
      { category: "MA3", club: "Madrid international disc golf", player: "Héctor Triano Alcántara", position: 10 },
      { category: "MA3", club: "Madrid international disc golf", player: "Nacho Ocho", position: 11 },
      { category: "MA3", club: "Asturias disc golf club", player: "Jorge Almeida", position: 11 },
      { category: "MA4", club: "Madrid international disc golf", player: "Arturo García Rodrigo", position: 1 },
      { category: "MA4", club: "Madrid international disc golf", player: "Rubén Hoya", position: 2 },
      { category: "MA4", club: "Disc golf club Oviedo", player: "José Francisco Hernández López", position: 3 },
      { category: "MA4", club: "Osona discgolf", player: "Ferran Boix Piella", position: 4 },
      { category: "MA4", club: "Madrid international disc golf", player: "Rimu Stille", position: 5 },
      { category: "MA4", club: "Disc golf club Oviedo", player: "Javier Lorences Fernandez", position: 6 },
      { category: "MA4", club: "Disc golf club Oviedo", player: "Hernán Fernández Joglar", position: 7 },
      { category: "MA4", club: "Disc golf club Oviedo", player: "Marcos Garcia Almeida", position: 8 },
      { category: "MA4", club: "Madrid international disc golf", player: "Dennis Neiman", position: 9 },
      { category: "MA4", club: "Esperit disc golf club", player: "Enric de Pablo", position: 10 },
      { category: "MA4", club: "Madrid international disc golf", player: "John Turcany", position: 11 },
      { category: "MA4", club: "Madrid international disc golf", player: "Francisco Panero", position: 12 },
      { category: "MA4", club: "Madrid international disc golf", player: "Miguel Angel Moral", position: 13 },
      { category: "MA4", club: "Madrid international disc golf", player: "Eduardo Martín Manzanera", position: 14 },
      { category: "MJ18", club: "Esperit disc golf club", player: "Lucas Gómez Feijoo", position: 1 }
    ]
  },
  {
    "id": 3,
    "name": "IV Abierto de Chipiona",
    "results": [
      { category: "MPO", club: "Lekunberri Kirol Elkartea", player: "Rafael Sarriegui Hidalgo", position: 3 },
      { category: "MPO", club: "Toros Mijas", player: "Andreas Havnegjerde", position: 1 },
      { category: "MPO", club: "Asturias disc golf club", player: "Manuel Domínguez Gallardo", position: 2 },
      { category: "MPO", club: "Disc golf club Oviedo", player: "Gorka Beltran de Heredia Alvarez", position: 5 },
      { category: "MPO", club: "Madrid international disc golf", player: "Martin Murray", position: 7 },
      { category: "MPO", club: "Esperit disc golf club", player: "Marc Lopez Lopez", position: 4 },
      { category: "MPO", club: "Disc golf club Oviedo", player: "Carlos Fernandez Ortega", position: 6 },
      { category: "FPO", club: "Toros Mijas", player: "Sanna Ahlgren", position: 1 },
      { category: "FPO", club: "Toros Mijas", player: "Leah Bizier", position: 2 },
      { category: "FPO", club: "Lekunberri Kirol Elkartea", player: "Lorea Zulet Ruiz", position: 3 },
      { category: "MP40", club: "Madrid international disc golf", player: "Robert Abel", position: 5 },
      { category: "MP40", club: "Toros Mijas", player: "Juha Kytö", position: 1 },
      { category: "MP40", club: "Toros Mijas", player: "Ari Koski-Vähälä", position: 2 },
      { category: "MP40", club: "Toros Mijas", player: "Tero Kolunsarka", position: 3 },
      { category: "MP40", club: "Compostela disc golf club", player: "Manuel Angel Almeida Posada", position: 4 },
      { category: "MP50", club: "Toros Mijas", player: "Geir Bengtsson", position: 1 },
      { category: "MP50", club: "Toros Mijas", player: "Sami Alm", position: 2 },
      { category: "MP50", club: "Asturias disc golf club", player: "Germán Dominguez Pimentel", position: 3 },
      { category: "MP50", club: "Asturias disc golf club", player: "Manuel Dominguez Pimentel", position: 4 },
      { category: "MP50", club: "Madrid international disc golf", player: "Toni Barrientos", position: 5 },
      { category: "MP50", club: "Esperit disc golf club", player: "Eloy Gomez Ingelmo", position: 6 },
      { category: "MP50", club: "Puerta de Doñana", player: "Leonardo Montilla", position: 7 },
      { category: "MP50", club: "Puerta de Doñana", player: "Eduardo Dominguez Vidal", position: 7 },
      { category: "MP50", club: "Madrid international disc golf", player: "Ismael Rodriguez", position: 9 },
      { category: "MP50", club: "Puerta de Doñana", player: "Francisco Guirado", position: 10 },
      { category: "MA3", club: "Toros Mijas", player: "Sebastian Döde", position: 1 },
      { category: "MA3", club: "Madrid international disc golf", player: "Hugo Rodriguez Fernandez", position: 1 },
      { category: "MA3", club: "Madrid international disc golf", player: "Rubén Hoya", position: 3 },
      { category: "MA3", club: "Toros Mijas", player: "Nicolai Aasen", position: 3 },
      { category: "MA3", club: "Madrid international disc golf", player: "Luis Andrés Aspe von Essen", position: 5 },
      { category: "MA3", club: "Toros Mijas", player: "Mikko Wikman", position: 5 },
      { category: "MA3", club: "Toros Mijas", player: "Niko Uusitalo", position: 7 },
      { category: "MA3", club: "Puerta de Doñana", player: "Lorenzo García Ramírez", position: 8 },
      { category: "MA3", club: "Puerta de Doñana", player: "Christian Palomeque", position: 9 },
      { category: "MA3", club: "Asturias disc golf club", player: "Jorge Almeida", position: 10 },
      { category: "MA4", club: "Disc golf club Oviedo", player: "José Francisco Hernández López", position: 1 },
      { category: "MA4", club: "Disc golf club Oviedo", player: "Javier Lorences Fernandez", position: 2 },
      { category: "MJ18", club: "Esperit disc golf club", player: "Lucas Gómez Feijoo", position: 1 }
    ]
  }, {
    "id": 4,
    "name": "V Open Xacobeo",
    "results": [
      { category: "MPO", club: "Asturias disc golf club", player: "Leon Blanco", position: 1 },
      { category: "MPO", club: "Asturias disc golf club", player: "Manuel Domínguez Gallardo", position: 2 },
      { category: "MPO", club: "Lekunberri Kirol Elkartea", player: "Rafael Sarriegui Hidalgo", position: 3 },
      { category: "MPO", club: "Disc golf club Oviedo", player: "Daniel Díaz Castro", position: 4 },
      { category: "FPO", club: "Asturias disc golf club", player: "Ana María Álvarez Menendez", position: 1 },
      { category: "MP40", club: "Compostela disc golf club", player: "Manuel Angel Almeida Posada", position: 1 },
      { category: "MP40", club: "Compostela disc golf club", player: "Iván Gutiérrez De Terán", position: 2 },
      { category: "MP40", club: "Compostela disc golf club", player: "Alejandro Liz Graña", position: 3 },
      { category: "MP40", club: "Compostela disc golf club", player: "Jacobo Morais Maceira", position: 4 },
      { category: "MP50", club: "Compostela disc golf club", player: "Alejandro Caporale", position: 1 },
      { category: "MA3", club: "Madrid international disc golf", player: "Pepe García", position: 1 },
      { category: "MA3", club: "Asturias disc golf club", player: "Jorge Almeida", position: 2 },
      { category: "MA3", club: "Compostela disc golf club", player: "Jorge Suarez de lis", position: 3 }, 
      { category: "MA4", club: "Disc golf club Oviedo", player: "José Francisco Hernández López", position: 1 },
      { category: "MA4", club: "Disc golf club Oviedo", player: "Francisco Leonardo Fagundes dos Santos", position: 2 },
      { category: "MA4", club: "Compostela disc golf club", player: "Carlos Rubio Estrada", position: 3 },
      { category: "MA4", club: "Disc golf club Oviedo", player: "Hernán Fernández Joglar", position: 4 },
      { category: "MA4", club: "Disc golf club Oviedo", player: "Javier Lorences Fernandez", position: 5 },
      { category: "MA4", club: "Disc golf club Oviedo", player: "Germán Muñoz Nacarino", position: 6 }
    ]
  }, {
    "id": 5,
    "name": "V Navarra Open - Nafarroako Irekia",
    "results": [
      { category: "MPO", club: "Disc golf club Oviedo", player: "Carlos Fernandez Ortega", position: 1 },
      { category: "MPO", club: "Esperit disc golf club", player: "Marc Lopez Lopez", position: 2 },
      { category: "MPO", club: "Disc golf club Oviedo", player: "Gorka Beltran de Heredia Alvarez", position: 3 },
      { category: "MPO", club: "Puerta de Doñana", player: "Miguel Espiau", position: 4 },
      { category: "MPO", club: "Disc golf club Oviedo", player: "Miguel Caparrós", position: 5 },
      { category: "MPO", club: "Puerta de Doñana", player: "Victor Parejo Ávila", position: 6 },
      { category: "FPO", club: "Esperit disc golf club", player: "Celia Aranda Reina", position: 1 },
      { category: "FPO", club: "Lekunberri Kirol Elkartea", player: "Lorea Zulet Ruiz", position: 2 },
      { category: "FPO", club: "Baxi Basajauna disc golf Elkartea", player: "Elixabete Lorenzo Borda", position: 3 },
      { category: "FPO", club: "Madrid international disc golf", player: "Vanessa Fernandez Fernandez", position: 4 },
      { category: "MP40", club: "Bilbao disc golf club", player: "Calixto García Velasco", position: 1 },
      { category: "MP40", club: "Esperit disc golf club", player: "David Wilde", position: 2 },
      { category: "MP50", club: "Baxi Basajauna disc golf Elkartea", player: "Iñaki Gonzalez Olaizola", position: 1 }, 
      { category: "MP50", club: "Disc golf club Oviedo", player: "Raúl López-Cancio Marínez", position: 2 },
      { category: "MP50", club: "Disc golf club Oviedo", player: "Javier Del Riego", position: 2 },
      { category: "MP50", club: "Baxi Basajauna disc golf Elkartea", player: "Antonio Negrete Gutiérrez", position: 4 },
      { category: "MP50", club: "Baxi Basajauna disc golf Elkartea", player: "Mikel Ibarrola Manterola", position: 5 },
      { category: "MP50", club: "Madrid international disc golf", player: "Toni Barrientos", position: 6 },
      { category: "MP50", club: "Madrid international disc golf", player: "Ismael Rodriguez", position: 7 }
      { category: "MA3", club: "Madrid international disc golf", player: "Hugo Rodriguez Fernandez", position: 1 }, 
      { category: "MA3", club: "Esperit disc golf club", player: "Daniel Aguilar Velez", position: 2 },
      { category: "MA4", club: "Disc golf club Oviedo", player: "José Francisco Hernández López", position: 1, },
      { category: "MA4", club: "Disc golf club Oviedo", player: "Hernán Fernández Joglar", position: 2 },
      { category: "MA4", club: "Esperit disc golf club", player: "Enric de Pablo Morales", position: 3 },
    ]
  }
];

/* TEMPLATE
[
  {
    "id": 1,
    "name": "Tournament 1",
    "results": [
      { category: "MPO", club: "Lekunberri Kirol Elkartea", player: "Rafael Sarriegui Hidalgo", position: null },
      { category: "MPO", club: "Lekunberri Kirol Elkartea", player: "Kristopher Vanbogelen", position: null },
      { category: "MPO", club: "Toros Mijas", player: "Markus Pohjolainen", position: null },
      { category: "MPO", club: "Esperit disc golf club", player: "Marc Lopez Lopez", position: null },
      { category: "MPO", club: "Disc golf club Oviedo", player: "Gorka Beltran de Heredia Alvarez", position: null },
      { category: "MPO", club: "Madrid international disc golf", player: "Martin Murray", position: null },
      { category: "MPO", club: "Flying squirrels", player: "Merlin Sales-Tomas Sales", position: null },
      { category: "MPO", club: "Madrid international disc golf", player: "Jorge BerÁstegui-Sampedro", position: null },
      { category: "FPO", club: "Lekunberri Kirol Elkartea", player: "Lorea Zulet Ruiz", position: null },
      { category: "FPO", club: "Asturias disc golf club", player: "Ana María Álvarez Menendez", position: null },
      { category: "FPO", club: "Osona discgolf", player: "Queralt Pinyol", position: null },
      { category: "FPO", club: "Madrid international disc golf", player: "Vanessa Fernandez Fernandez", position: null },
      { category: "MP40", club: "Madrid international disc golf", player: "Robert Abel", position: null },
      { category: "MP40", club: "Compostela disc golf club", player: "Iván Gutiérrez De Terán", position: null },
      { category: "MP40", club: "Compostela disc golf club", player: "Manuel Angel Almeida Posada", position: null },
      { category: "MP40", club: "Esperit disc golf club", player: "David Wilde", position: null },
      { category: "MP40", club: "Osona discgolf", player: "Marc Font Font", position: null },
      { category: "MP40", club: "Compostela disc golf club", player: "Alejandro Liz Graña", position: null },
      { category: "MP50", club: "Bilbao disc golf club", player: "David Angulo", position: null },
      { category: "MP50", club: "Baxi Basajauna disc golf Elkartea", player: "Mikel Ibarrola Manterola", position: null },
      { category: "MP50", club: "Bilbao disc golf club", player: "Jose Sampedro Santin", position: null },
      { category: "MP50", club: "Baxi Basajauna disc golf Elkartea", player: "Iñaki González Olaizola", position: null },
      { category: "MP50", club: "Disc golf club Oviedo", player: "Javier Del Riego", position: null },
      { category: "MP50", club: "Madrid international disc golf", player: "Toni Barrientos", position: null },
      { category: "MP50", club: "Baxi Basajauna disc golf Elkartea", player: "Antonio Negrete Gutiérrez", position: null },
      { category: "MP50", club: "Esperit disc golf club", player: "Eloy Gomez Ingelmo", position: null },
      { category: "MP50", club: "Madrid international disc golf", player: "Ismael Rodriguez", position: null },
      { category: "MA3", club: "Madrid international disc golf", player: "Hugo Rodriguez Fernandez", position: null },
      { category: "MA3", club: "Compostela disc golf club", player: "Pedro Gonzalez Bascoy", position: null },
      { category: "MA3", club: "Disc golf club Oviedo", player: "Daniel Díaz Castro", position: null },
      { category: "MA3", club: "Madrid international disc golf", player: "Fraser Ambrose", position: null },
      { category: "MA3", club: "Madrid international disc golf", player: "Armando Del Olmo", position: null },
      { category: "MA3", club: "Madrid international disc golf", player: "Juan Aramburu", position: null },
      { category: "MA3", club: "Madrid international disc golf", player: "Nelson Zurdo", position: null },
      { category: "MA3", club: "Madrid international disc golf", player: "Stefan Nestelberger", position: null },
      { category: "MA3", club: "Madrid international disc golf", player: "Pepe García", position: null },
      { category: "MA3", club: "Madrid international disc golf", player: "Lucas Rey Braga", position: null },
      { category: "MA3", club: "Madrid international disc golf", player: "Héctor Triano Alcántara", position: null },
      { category: "MA3", club: "Madrid international disc golf", player: "Nacho Ocho", position: null },
      { category: "MA3", club: "Asturias disc golf club", player: "Jorge Almeida", position: null },
      { category: "MA4", club: "Bilbao disc golf club", player: "Asier Merino Lekue", position: null },
      { category: "MA4", club: "Madrid international disc golf", player: "Arturo García Rodrigo", position: null },
      { category: "MA4", club: "Madrid international disc golf", player: "Rubén Hoya", position: null },
      { category: "MA4", club: "Disc golf club Oviedo", player: "José Francisco Hernández López", position: null },
      { category: "MA4", club: "Osona discgolf", player: "Ferran Boix Piella", position: null },
      { category: "MA4", club: "Disc golf club Oviedo", player: "Javier Lorences Fernandez", position: null },
      { category: "MA4", club: "Disc golf club Oviedo", player: "Hernán Fernández Joglar", position: null },
      { category: "MA4", club: "Disc golf club Oviedo", player: "Marcos Garcia Almeida", position: null },
      { category: "MA4", club: "Madrid international disc golf", player: "Dennis Neiman", position: null },
      { category: "MA4", club: "Madrid international disc golf", player: "John Turcany", position: null },
      { category: "MA4", club: "Madrid international disc golf", player: "Francisco Panero", position: null },
      { category: "MA4", club: "Madrid international disc golf", player: "Miguel Angel Moral", position: null },
      { category: "MA4", club: "Madrid international disc golf", player: "Eduardo Martín Manzanera", position: null },
      { category: "MA4", club: "Esperit disc golf club", player: "Enric de Pablo", position: null },
      { category: "MJ18", club: "Bilbao disc golf club", player: "Beñat Lopez Arribas", position: null },
      { category: "MJ18", club: "Esperit disc golf club", player: "Lucas Gómez Feijoo", position: null }
    ]
  },
]

 
 */
